### ISSUE TITLE
Add Github CI checks for linting etc

### ISSUE THREAD

**Issue by norswap** [0xFableOrg/0xFable#119]
We should run the global makefile's `make check` in [github CI](https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-ci-checks-with-a-github-app) and ensure it exits with a zero error code (meaning everything passed as expected).

Here's [an example of the same thing in the roll-op repo](https://github.com/0xFableOrg/roll-op/blob/master/.github/workflows/build.yml).

Note that we don't need to "build": the contracts tests will build them automatically, and the typescript code doesn't need a build step. HOWEVER, we will need `make setup` first to install all dependencies.

**Comment by intldds** [comment]
Would love to tackle this one : )

**Comment by ptisserand** [comment]
Hi, can I take this issue?

**Comment by ptisserand** [comment]
Should I include fix for typescript linter issue in my PR or is it better to have another one to ensure that linter issues are detected by CI ?

**Comment by norswap** [comment]
> Should I include fix for typescript linter issue in my PR or is it better to have another one to ensure that linter issues are detected by CI ?

It can be in the same PR if there are some remaining linting issues, just make sure they're in separate commits!
