### ISSUE TITLE
Switch to ConnectKit?

### ISSUE THREAD

**Issue by norswap** [0xFableOrg/0xFable#18]
I've been less than super impressed with WalletConnect, and I've noticed a lot of people that seem to know what's up using ConnectKit. So could be worth trying the integration.

**Comment by AhmadDecoded** [comment]
Was going through the ConnectKit docs, under the hood they using the Wallet Connect too as the doc mentions:

**ConnectKit utilises [WalletConnect](https://walletconnect.com/)'s SDK to help with connecting wallets. WalletConnect 2.0 requires a projectId which you can create quickly and easily for free over at [WalletConnect Cloud](https://cloud.walletconnect.com/sign-in).**

**Comment by norswap** [comment]
Ah, sorry, I was imprecise in the issue.

We're currently using Web3Modal, which is a wallet flow/UX library implemented by the WalletConnect team. I should have said "Web3Modal" instead of "WalletConnect".

WalletConnect itself is a protocol for wallet interop, notably via QR codes (I know rather less than I should there). We most definitely want to use a wallet flow library that supports WalletConnect, but it does not have to be Web3Modal :)

**Comment by norswap** [comment]
Web3Modal is now spamming my console with

```
Firefox can’t establish a connection to the server at wss://u.bridge.walletconnect.org/?env=browser&host=localhost%3A3000&protocol=wc&version=1.
```

(same on chrome, though different message)

Piece of garbage :')

**Comment by norswap** [comment]
I updated Web3Modal today and it does not pick up on Metamask, so I'm going ahead with this one.

For posterity's sake, here's how to make the the new version of web3modal "work" (besides that metamask issue):

```
/**
 * The wagmi public client, used to read from the blockchain. This can be accessed via wagmi's
 * `getPublicClient` action.
 */
const { publicClient: wagmiPublicClient } =
  configureChains(chains, [
    walletConnectProvider({ projectId: walletConnectProjectId }),
    publicProvider() // needed for localhost
  ])

export const wagmiConfig = createConfig({
  // Note: must be set to false for the (Metamask-enabled) e2e tests to work.
  autoConnect: true,
  connectors: [
      new WalletConnectConnector({
        chains,
        options: {
          projectId: walletConnectProjectID,
          showQrModal: false,
          metadata: {
            name: "0xFable",
            description: "Fantasy & Shit",
            url: "https://0xFable.org",
            icons: []
          } }
      }),
    // ...burnerConnectors
  ],
  publicClient: wagmiPublicClient
})
```
