### ISSUE TITLE
Try using Vite instead of Next.js

### ISSUE THREAD

**Issue by norswap** [0xFableOrg/0xFable#43]
Currently we use Next.js for building and routing. Next has been rather easy to work with, but it has two disadvantages:

- The dev source maps are super shitty (mapping into big js bundles, and poorly), making debugging harder than it needs to be.
      - To make matters worse, Next aggressively prevents you from changing the source map provider.
- We don't need server-side rendering (we have no server outside the blockchain, and I don't foresee this would be a big need) but need to worry about hydration issues nonetheless (this is rather easy to sidestep with the custom `useIsHydrated` hook, but it's still a bit janky). Pretty minor issue though.

I've heard that Vite has clean source maps, so I'm interested to try it out and compare.

Swapping out Next also means we need an alternative routing solution — something like react-router maybe? Open to alternatives as long as it's fairly lightweight and doesn't pull in a bunch of stuff we don't need.

**Comment by cwkang1998** [comment]
I think something like `vite` + `react` + `react-router` is going to be okay. Not very sure about the exact bundle size but I can try it out and give a comparison.

**Comment by Xaxxoo** [comment]
@norswap  I would like to handle this.

**Comment by norswap** [comment]
I think this is no longer a priority at this point, we have a good way to avoid server-side rendering issues (`useIsHydrated`) and the source map seem to work now.

It would also force us to change the way we handle routing, which we have customized quite a bit for passing around extra parameters (which enable sending transaction with an in-browser private key for testing purposes).

I'm sorry about the confusion, I'll be closing this now!
